### ISSUE TITLE
Soddisfacibilità delle formule in ML

### ISSUE THREAD

**Issue by gekoramy** [gik98/unitn18-logics#1]
Nel testo compare
<img width="814" alt="schermata 2018-12-16 alle 13 26 56" src="https://user-images.githubusercontent.com/20395895/50053545-4725cf00-0137-11e9-9103-b10213bedec9.png">

Tale osservazione è contraddetta dalla soluzione di un esercizio
![2018-12-16 13 28 09](https://user-images.githubusercontent.com/20395895/50053549-6ae91500-0137-11e9-8ee1-1f6be90302f3.jpg)

**Comment by gik98** [comment]
Uh certo. È sbagliata anche l'altra osservazione, o meglio, sono invertite.
box phi è necessariamente vero, diamond phi è necessariamente falso
