### ISSUE TITLE
Typo pagina 4 definizione di compactness

### ISSUE THREAD

**Issue by Momofil31** [gik98/unitn18-logics#2]
Segnalo typo a pagina 4 nella definizione di compactness:
Dovrebbe essere "if \Gamma" invece di "if \Sigma"

![photo_2019-10-29_14-06-18](https://user-images.githubusercontent.com/11832130/67769737-4ba85d00-fa55-11e9-9c7d-259ceafa234f.jpg)

**Comment by gik98** [comment]
Corretto, grazie :+1:
